CREATE OR ALTER  VIEW VW_OPERACIONALDOCUMENTOS AS 
SELECT DISTINCT
DOC.DOCID AS DOCUMENTOID,
DOC.NUMERODOC AS NUMERODOCUMENTO,
DOC.SERIE AS SERIE,
DOC.DATAEMISSAO AS DATAEMISSAO,
DOC.LOCALENTREGACIDADE AS LOCALENTREGACIDADE,
DOC.LOCALENTREGAUF AS LOCALENTREGAUF,
DOC.DATACADASTRO AS DATACADASTRO,
DOC.FILIALID AS FILIALORIGEMID,
FILORIGEM.SIGLA AS FILIALORIGEMSIGLA,
DOC.TIPODOCUMENTOID AS TIPODOCUMENTOID,
TIPODOC.IDENTIFICADOR AS TIPODOCUMENTOIDENTIFICADOR,
DOC.STATUSDOCUMENTOID AS STATUSDOCUMENTOID,
STDOCUMENTO.DESCRICAO AS STATUSDOCUMENTODESCRICAO,
STDOCUMENTO.SIGLA AS STATUSDOCUMENTOSIGLA,
DOC.PRODUTOID AS PRODUTOID,
COMPFRETE.VALORMERCADORIA AS VALORMERCADORIA,
COMPFRETE.PESO AS PESO,
COMPFRETE.PESOCUBADO AS PESOCUBADO,
COMPFRETE.TOTALFRETE AS TOTALFRETE,
DOC.REMETENTEID AS REMETENTEID,
CLIREM.CPFCNPJ AS REMETENTECPFCNPJ,
CLIREM.NOMEFANTASIA AS REMETENTENOMEFANTASIA,
DOC.DESTINATARIOID AS DESTINATARIOID,
CLIDEST.CPFCNPJ AS DESTINATARIOCPFCNPJ,
CLIDEST.NOMEFANTASIA AS DESTINATARIONOMEFANTASIA,
DOC.EXPEDIDORID AS EXPEDIDORID,
DOC.RECEBEDORID AS RECEBEDORID,
DOC.REDESPACHOID AS REDESPACHOID,
DOC.TOMADORID AS TOMADORID,
DOC.TIPOFRETEID AS TIPOFRETEID,
TPFRETE.TIPOFRETEDESC AS TIPOFRETEDESC,
(SELECT TOP 1 NUMERONOTA FROM DOCUMENTONOTA DN1 WHERE  DN1.DOCID = DOC.DOCID AND DN1.CLIENTEID = DOC.REMETENTEID) AS NUMERONOTAFISCAL,
(SELECT SUM(VOLUMES) FROM DOCUMENTONOTA DN WHERE DN.DOCID = DOC.DOCID AND DN.CLIENTEID = DOC.REMETENTEID) AS VOLUMES
FROM DOCUMENTOS DOC 
INNER JOIN DOCDESTINATARIO CLIDEST ON CLIDEST.DOCID = DOC.DOCID AND CLIDEST.CLIENTEID = DOC.DESTINATARIOID
INNER JOIN DOCREMETENTE CLIREM ON CLIREM.DOCID = DOC.DOCID AND CLIREM.CLIENTEID = DOC.REMETENTEID
INNER JOIN DOCUMENTOSCOMPOSICAOFRETE COMPFRETE ON COMPFRETE.DOCID = DOC.DOCID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FILORIGEM ON FILORIGEM.FILIALID = DOC.FILIALID
INNER JOIN SITRAWEBNEW.DBO.TIPODOCUMENTO TIPODOC ON TIPODOC.TIPODOCUMENTOID = DOC.TIPODOCUMENTOID
INNER JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTO STDOCUMENTO ON STDOCUMENTO.STATUSDOCUMENTOID = DOC.STATUSDOCUMENTOID
LEFT JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTOSEFAZ STDOCUMENTOSEFAZ ON STDOCUMENTOSEFAZ.STATUSDOCUMENTOSEFAZID = DOC.STATUSDOCUMENTOSEFAZID
INNER JOIN SITRAWEBNEW.DBO.TIPOFRETE TPFRETE ON TPFRETE.TIPOFRETEID = DOC.TIPOFRETEID
INNER JOIN DOCUMENTONOTA DOCNOTA ON DOC.DOCID = DOCNOTA.DOCID AND DOCNOTA.CLIENTEID = DOC.REMETENTEID 
WHERE 
(DOC.NUMEROTEMPORARIO IS NULL)
AND ((DOC.TIPODOCUMENTOID = 1 AND DOC.STATUSDOCUMENTOSEFAZID IS NOT NULL AND DOC.STATUSDOCUMENTOSEFAZID NOT IN (1,2,3,4,6,7,8,10)) OR DOC.TIPODOCUMENTOID = 5)
GO
ALTER VIEW VW_OPERACIONALMANIFESTOS AS
SELECT DISTINCT

DOC.DOCID AS DOCUMENTOID,
DOC.NUMERODOC AS NUMERODOCUMENTO,
DOC.SERIE AS SERIE,
DOC.DATAEMISSAO AS DATAEMISSAO,
DOC.LOCALENTREGACIDADE AS LOCALENTREGACIDADE,
DOC.LOCALENTREGAUF AS LOCALENTREGAUF,
ESTUF.REGIAO AS REGIAOENTREGA,
DOC.LOCALCOLETAUF AS LOCALCOLETAUF,
ESTUF2.REGIAO AS REGIAOCOLETA,
DOC.DATACADASTRO AS DATACADASTRO,
DOC.FILIALID AS FILIALORIGEMID,
FILORIGEM.SIGLA AS FILIALORIGEMSIGLA,
DOC.TIPODOCUMENTOID AS TIPODOCUMENTOID,
CASE WHEN
	TIPODOC.IDENTIFICADOR = 'C' THEN 'CONHECIMENTO (CT-E)'
	WHEN TIPODOC.IDENTIFICADOR = 'M' THEN 'MINUTA (MD-E)' ELSE ''
END  AS TIPODOCUMENTOIDENTIFICADOR,
DOC.STATUSDOCUMENTOID AS STATUSDOCUMENTOID,
STDOCUMENTO.DESCRICAO AS STATUSDOCUMENTODESCRICAO,
STDOCUMENTO.SIGLA AS STATUSDOCUMENTOSIGLA,
DOC.PRODUTOID AS PRODUTOID,
COMPFRETE.VALORMERCADORIA AS VALORMERCADORIA,
COMPFRETE.PESO AS PESO,
COMPFRETE.PESOCUBADO AS PESOCUBADO,
COMPFRETE.TOTALFRETE AS TOTALFRETE,
DOC.REMETENTEID AS REMETENTEID,
CLIREM.CPFCNPJ AS REMETENTECPFCNPJ,
CLIREM.NOMEFANTASIA AS REMETENTENOMEFANTASIA,
DOC.DESTINATARIOID AS DESTINATARIOID,
CLIDEST.CPFCNPJ AS DESTINATARIOCPFCNPJ,
CLIDEST.NOMEFANTASIA AS DESTINATARIONOMEFANTASIA,
DOC.EXPEDIDORID AS EXPEDIDORID,
DOC.RECEBEDORID AS RECEBEDORID,
DOC.REDESPACHOID AS REDESPACHOID,
DOC.TOMADORID AS TOMADORID,
DOC.TIPOFRETEID AS TIPOFRETEID,
TPFRETE.TIPOFRETEDESC AS TIPOFRETEDESC,
(SELECT TOP 1 NUMERONOTA FROM DOCUMENTONOTA DN1 WHERE   DN1.DOCID = DOC.DOCID AND DN1.CLIENTEID = DOC.REMETENTEID) AS NUMERONOTAFISCAL,
(SELECT SUM(VOLUMES) FROM DOCUMENTONOTA DN WHERE DN.DOCID = DOC.DOCID AND DN.CLIENTEID = DOC.REMETENTEID) AS VOLUMES
FROM DOCUMENTOS DOC 
INNER JOIN DOCDESTINATARIO CLIDEST ON CLIDEST.DOCID = DOC.DOCID AND CLIDEST.CLIENTEID = DOC.DESTINATARIOID
INNER JOIN DOCREMETENTE CLIREM ON CLIREM.DOCID = DOC.DOCID AND CLIREM.CLIENTEID = DOC.REMETENTEID
INNER JOIN DOCUMENTOSCOMPOSICAOFRETE COMPFRETE ON COMPFRETE.DOCID = DOC.DOCID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FILORIGEM ON FILORIGEM.FILIALID = DOC.FILIALID
INNER JOIN SITRAWEBNEW.DBO.TIPODOCUMENTO TIPODOC ON TIPODOC.TIPODOCUMENTOID = DOC.TIPODOCUMENTOID
INNER JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTO STDOCUMENTO ON STDOCUMENTO.STATUSDOCUMENTOID = DOC.STATUSDOCUMENTOID
LEFT JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTOSEFAZ STDOCUMENTOSEFAZ ON STDOCUMENTOSEFAZ.STATUSDOCUMENTOSEFAZID = DOC.STATUSDOCUMENTOSEFAZID
INNER JOIN SITRAWEBNEW.DBO.TIPOFRETE TPFRETE ON TPFRETE.TIPOFRETEID = DOC.TIPOFRETEID
INNER JOIN DOCUMENTONOTA DOCNOTA ON DOC.DOCID = DOCNOTA.DOCID AND DOCNOTA.CLIENTEID = DOC.REMETENTEID 
INNER JOIN SITRAWEBNEW.DBO.ESTADOS AS ESTUF ON ESTUF.UF = DOC.LOCALENTREGAUF
INNER JOIN SITRAWEBNEW.DBO.ESTADOS AS ESTUF2 ON ESTUF2.UF = DOC.LOCALCOLETAUF
WHERE 
(DOC.NUMEROTEMPORARIO IS NULL)
AND (DOC.TIPODOCUMENTOID = 1 AND DOC.STATUSDOCUMENTOSEFAZID IS NOT NULL AND DOC.STATUSDOCUMENTOSEFAZID NOT IN (1,2,3,4,6,7,8,10))
GO