CREATE OR ALTER  VIEW VW_SELECTMONITORAMENTOMDFE AS 
SELECT DISTINCT
MAE.MANIFESTOID
,FIL.SIGLA		 FILIAL
,MAN.NRMANIFESTO NUMERO
,MAN.SERIE SERIE
,MAN.DATACADASTRO DATAEMISSAO
,ST.SIGLA STATUSSEFAZ
,CASE WHEN STP.SIGLA = 'IT' THEN 'AR'
	  WHEN STP.SIGLA = 'VL' THEN 'AE'
	  WHEN STP.SIGLA = 'PE' THEN 'AE'
	  ELSE STP.SIGLA
 END STATUSPROCESSAMENTO
,CASE WHEN COALESCE(MAE.MENSAGEM,'') = '' 
      THEN CASE WHEN COALESCE(ST.DESCRICAO,'') = '' 
	            THEN CASE WHEN STP.SIGLA = 'IT' THEN 'AGUARDANDO RETORNO'
						  WHEN STP.SIGLA = 'VL' THEN 'AGUARDANDO ENVIO'
						  WHEN STP.SIGLA = 'PE' THEN 'AGUARDANDO ENVIO'
						  ELSE STP.DESCRICAO 
					 END
				ELSE CASE WHEN ST.SIGLA = 'IT' THEN 'AGUARDANDO RETORNO'
						  WHEN ST.SIGLA = 'VL' THEN 'AGUARDANDO ENVIO'
						  WHEN ST.SIGLA = 'PE' THEN 'AGUARDANDO ENVIO'
						  ELSE ST.DESCRICAO
					  END
		   END 
	  ELSE MAE.MENSAGEM 
  END AS SITUACAO
,MAE.CHAVEACESSO
,CASE WHEN MAE.AMBIENTE = 1 THEN '1 - PRODUÇÃO' ELSE '2 - HOMOLOGAÇÃO' END AS TIPOEMISSAO
,MAN.PLACAVEICULO VEICULO
,MAE.UFCARREGAMENTO ORIGEM
,MAE.UFDESCARREGAMENTO DESTINO
,CASE WHEN MAE.DATAHRAUTORIZACAOSEFAZ IS NULL THEN MAE.DATAAUTORIZACAO ELSE MAE.DATAHRAUTORIZACAOSEFAZ END AS DATAAUTORIZACAO
,MAE.NRPROTOCOLOAUTORIZACAO
,MAE.NRPROTOCOLOCANCELAMENTO
,MAE.NRPROTOCOLOENCERRAMENTO
,USU.USUARIONOME USUARIO
,FIL.RAZAOSOCIAL EMITENTE

,CASE 	
	WHEN STP.SIGLA = 'RJ' THEN 1
	WHEN STP.SIGLA = 'EG' THEN 2
	WHEN STP.SIGLA = 'PE' THEN 3
	WHEN STP.SIGLA = 'VL' THEN 4
	WHEN STP.SIGLA = 'IT' THEN 5
	WHEN STP.SIGLA = 'AT' THEN 6
	WHEN STP.SIGLA = 'CA' THEN 7
	WHEN STP.SIGLA = 'EC' THEN 8
END AS ORDERNACAO
,CASE 	
		WHEN MAN.TIPODOCUMENTOID = 2 THEN 'MANIFESTO ELETRONICO MDF-e'
		WHEN MAN.TIPODOCUMENTOID = 7 THEN 'MANIFESTO MINUTA MDM' END AS TIPOMANIFESTO

FROM MANIFESTO MAN
INNER JOIN MANIFESTOELETRONICO MAE ON MAE.MANIFESTOID = MAN.MANIFESTOID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FIL  ON FIL.FILIALID = MAN.FILIALID
LEFT JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTOSEFAZ ST ON ST.STATUSDOCUMENTOSEFAZID = MAE.STATUSDOCUMENTOSEFAZID
LEFT JOIN SITRAWEBNEW.DBO.STATUSPROCESSAMENTO STP ON STP.STATUSPROCESSAMENTOID = MAE.STATUSPROCESSAMENTOID
LEFT JOIN SITRAWEBNEW.DBO.USUARIOS USU ON USU.USUARIOID = MAN.USUARIOCADASTROID
GO
CREATE OR ALTER  VIEW VW_CONSULTARELATDOCSEMITIDOSEXCEL
AS SELECT  DISTINCT
	TD.SIGLA																									AS TIPO
	,FO.SIGLA																									AS FILIALORIGEM
	,D.NUMERODOC																								AS DOCUMENTO
	,D.SERIE																									AS SERIE
	,FD.SIGLA																									AS FILIALDESTINO
	,D.DATAEMISSAO																								AS DATAEMISSAO
	,SD.SIGLA																									AS STATUS
	,SD.DESCRICAO																								AS DESCRICAOSTATUS
	,(SELECT TOP 1 DHE.DATAHISTORICO FROM DOCUMENTOHISTORICO DHE 
		WHERE DHE.DOCID = D.DOCID AND DHE.TIPOHISTORICOID IN (1,5,14) ORDER BY DHE.DATACADASTRO DESC)			AS DATAENTEGA
	--,DHE.DATAHISTORICO																						AS DATAENTEGA
	,''																											AS HORAENTREGA
	,(SELECT TOP 1 DHE.RECEBEDORMERCADORIA FROM DOCUMENTOHISTORICO DHE 
		WHERE DHE.DOCID = D.DOCID AND DHE.TIPOHISTORICOID IN (1,5,14) ORDER BY DHE.DATACADASTRO DESC)			AS RECEBEDORMERCADORIA
	--,DHE.RECEBEDORMERCADORIA																					AS RECEBEDORMERCADORIA
	,TF.TIPOFRETEDESC																							AS TIPODEFRETE
	,DE.CPFCNPJ																									AS CNPJCOLETA
	,DE.NOMEFANTASIA																							AS NOMECOLETA
	,DE.CIDADE																									AS CIDADECOLETA
	,DE.UF																										AS UFCOLETA
	,DR.CPFCNPJ																									AS CNPJREMETENTE
	,DR.NOMEFANTASIA																							AS NOMEREMETENTE
	,DR.CIDADE																									AS CIDADEREMETENTE
	,DR.UF																										AS UFREMETENTE
	,DD.CPFCNPJ																									AS CNPJDESTINATARIO
	,DD.NOMEFANTASIA																							AS NOMEDESTINATARIO
	,DD.CIDADE																									AS CIDADEDESTINATARIO
	,DD.UF																										AS UFDESTINATARIO
	,DRE.CPFCNPJ																								AS CNPJRECEBEDOR
	,DRE.NOMEFANTASIA																							AS NOMERECEBEDOR
	,DRE.CIDADE																									AS CIDADERECEBEDOR
	,DRE.UF																										AS UFRECEBEDOR
	,DRP.CPFCNPJ																								AS CNPJREDESPACHO
	,DRP.NOMEFANTASIA																							AS NOMEREDESPACHO
	,DRP.CIDADE																									AS CIDADEREDESPACHO
	,DRP.UF																										AS UFREDESPACHO
	,DT.CPFCNPJ																									AS CNPJTOMADOR
	,DT.NOMEFANTASIA																							AS NOMETOMADOR
	,DT.CIDADE																									AS CIDADETOMADOR
	,DT.UF																										AS UFTOMADOR
	,(SELECT STUFF( (SELECT DISTINCT ', ' + CAST(DN.NUMERONOTA AS VARCHAR(15)) + ' - ' + DN.SERIE 
					  FROM DOCUMENTONOTA DN 
					  WHERE  DN.DOCID = D.DOCID AND DN.CLIENTEID = D.REMETENTEID FOR XML PATH ('')), 1, 2,''))	AS NOTASFISCAIS
	,(SELECT SUM(DN.VOLUMES) FROM DOCUMENTONOTA DN WHERE  DN.DOCID = D.DOCID AND DN.CLIENTEID = D.REMETENTEID)	AS VOLUMES
	,DCF.VALORMERCADORIA																						AS VALORMERCADORIA
	,DCF.PESO																									AS PESO
	,DCF.PESOCUBADO																								AS PESOCUBADO
	,DCF.FRETEPESO																								AS FRETEPESO
	,DCF.FRETEVALOR																								AS FRETEVALOR
	,DCF.CAT																									AS VALORDOCAT
	,DCF.DESPACHO																								AS VALORDESPACHO
	,DCF.PEDAGIO																								AS VALORPEDAGIO
	,DCF.GRIS																									AS GRIS
	,DCF.VALORSEGURO																							AS SEGURO
	,DCF.TAXACOLENT																								AS TAXACOLENT
	,DCF.TDE																									AS TDE
	,DCF.TRT																									AS TRT
	,DCF.OUTRASTAXAS																							AS OUTRASTAXAS
	,DCF.TOTALFRETE																								AS VALORFRETE
	,FAT.DESCONTOFATURAMENTO																					AS DESCONTO
	,DCF.TOTALFRETE - COALESCE(FAT.DESCONTOFATURAMENTO,0)														AS VALORLIQUIDO
	,NULL																										AS VALORFRETEPARCEIRO
	,D.BASECALCULOICMS																							AS BASEDECALCULOICMS
	,D.VALORICMS																								AS VALORICMS
	,D.ALIQUOTAICMS																								AS ALIQDEICMS	
	, CASE D.TIPOTRIBUTARIA WHEN 'N' THEN 'ICMS NORMAL'
							WHEN 'I' THEN 'ISENTO DE ICMS'                        
							WHEN 'S' THEN 'SUBST.TRIBUTÁRIA'                        
							WHEN 'P' THEN 'SIMPLES NACIONAL'                       
							WHEN 'G' THEN 'ICMS GNRE'
	  END																										AS TIPODEICMS
	,D.CFOP																										AS CFOP
	,D.CHAVEACESSO																								AS CHAVECTE
	,D.NATUREZA																									AS NATUREZA
	,D.ESPECIE																									AS ESPECIE
	,PRD.PRODUTODESC																							AS PRODUTOCALC
	,D.PLACAVEICULO																								AS PLACACAVALO
	,D.PLACACARRETA																								AS PLACACARRETA
	,MOT.NOME																									AS MOTORISTA
	,(SELECT STUFF((SELECT 
					DISTINCT ', ' + (UPPER(F.SIGLA) + ' - ' + 
										CAST(M.NRMANIFESTO AS VARCHAR(20)) + 
										'(' + UPPER(SDM.SIGLA) + ')')
				   FROM MANIFESTO_DOC MD 
					 INNER JOIN MANIFESTO M ON M.MANIFESTOID = MD.MANIFESTOID
					 INNER JOIN SITRAWEBNEW.DBO.FILIAIS F ON F.FILIALID = M.FILIALID
					 INNER JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTO SDM ON SDM.STATUSDOCUMENTOID = M.STATUSID
				   WHERE MD.DOCUMENTOID = D.DOCID FOR XML PATH ('')), 1, 2,''))									AS MANIFESTOS
	,COF.SIGLA																									AS FILIALCOTACAO
	,CO.NUMEROCOTACAO																							AS NUMEROCOTACAO
	,D.OBSERVACAO																								AS OBSERVACAO
	,(SELECT TOP 1 DHO.OBSERVACAO 
		FROM DOCUMENTOHISTORICO DHO 
		WHERE DHO.DOCID = D.DOCID AND DHO.TIPOHISTORICOID = 13 ORDER BY DHO.DATACADASTRO DESC)					AS OBSERVACAODEOCORRENCIA	
	,VEND.NOME																									AS VENDEDOR
	,CAST(REB.NUMEROFATURA AS VARCHAR(20)) + '/' +  CAST(REB.ANOFATURA AS VARCHAR(4))							AS FATURARECIBO
	,REB.DATAVENCIMENTO																							AS DATAVENCIMENTO
	,REB.DATAPRORROGACAO																						AS DATAPRORROGACAO
	,REB.DATAPAGAMENTO																							AS DATAPAGAMENTO
	,REB.VALORTOTAL																								AS VALORRECEBIDO
	,CB.CONTABANCARIA																							AS BANCOCREDITO
	,SR.SIGLA																									AS STATUSPAG
	,FAV.DATAPAGAMENTO																							AS DATAPAGAMENTOFAV
	,FAV.VALORPAGO																								AS VALORRECEBIDOFAV
	,CBFAV.CONTABANCARIA																						AS BANCOCREDITOFAV
	,SRFAV.SIGLA																								AS STATUSPAGFAV
FROM DOCUMENTOS D
INNER JOIN SITRAWEBNEW.DBO.TIPODOCUMENTO TD ON TD.TIPODOCUMENTOID = D.TIPODOCUMENTOID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FO ON FO.FILIALID = D.FILIALID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FD ON FD.FILIALID = D.FILIALDESTINOID
INNER JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTO SD ON SD.STATUSDOCUMENTOID = D.STATUSDOCUMENTOID
INNER JOIN SITRAWEBNEW.DBO.TIPOFRETE TF ON TF.TIPOFRETEID = D.TIPOFRETEID
LEFT JOIN DOCUMENTOHISTORICO  DHE ON DHE.DOCID = D.DOCID AND DHE.TIPOHISTORICOID IN (1,5,14)
LEFT JOIN DOCEXPEDIDOR DE ON DE.CLIENTEID = D.EXPEDIDORID AND DE.DOCID = D.DOCID
LEFT JOIN DOCREMETENTE DR ON DR.CLIENTEID = D.REMETENTEID AND DR.DOCID = D.DOCID
LEFT JOIN DOCDESTINATARIO DD ON DD.CLIENTEID = D.DESTINATARIOID AND DD.DOCID = D.DOCID
LEFT JOIN DOCRECEBEDOR DRE ON DRE.CLIENTEID = D.RECEBEDORID AND DRE.DOCID = D.DOCID
LEFT JOIN DOCREDESPACHO DRP ON DRP.CLIENTEID = D.REDESPACHOID AND DRP.DOCID = D.DOCID
LEFT JOIN DOCTOMADOR DT ON DT.CLIENTEID = D.TOMADORID AND DT.DOCID = D.DOCID
INNER JOIN DOCUMENTOSCOMPOSICAOFRETE DCF ON DCF.DOCID = D.DOCID
LEFT JOIN FATURAS FAT ON FAT.DOCUMENTOID = D.DOCID AND FAT.FILIALDOCUMENTOID = D.FILIALID AND FAT.TIPODOCUMENTOID = D.TIPODOCUMENTOID
INNER JOIN PRODUTOS PRD ON PRD.PRODUTOID = D.PRODUTOID
LEFT JOIN MOTORISTA MOT ON MOT.MOTORISTAID = D.MOTORISTAID
LEFT JOIN COTACAO CO ON CO.DOCID = D.DOCID AND CO.FILIALDOCID = D.FILIALID
LEFT JOIN SITRAWEBNEW.DBO.FILIAIS COF ON COF.FILIALID  = CO.FILIALID
LEFT JOIN CLIENTES CLITOM ON CLITOM.CLIENTEID = DT.CLIENTEID
LEFT JOIN VENDEDORES VEND ON VEND.VENDEDORID = CLITOM.VENDEDORID
LEFT JOIN RECEBIMENTO REB ON REB.ANOFATURA = FAT.ANOFATURA AND REB.NUMEROFATURA = FAT.NUMEROFATURA AND REB.CLIENTEPAGADORID = FAT.CLIENTEPAGADORDOCUMENTOID AND REB.FILIALEMISSAOFATURA = FAT.FILIALFATURAMENTOID
LEFT JOIN CONTABANCARIA CB ON CB.ID = REB.BANCOID
LEFT JOIN SITRAWEBNEW.DBO.STATUSRECEBIMENTO SR ON SR.ID = REB.STATUSRECEBIMENTOID
LEFT JOIN FRETEAVISTA FAV ON FAV.DOCUMENTOID = D.DOCID AND FAV.FILIALORIGEMID = D.FILIALID AND FAV.TIPODOCUMENTOID = D.TIPODOCUMENTOID
LEFT JOIN CONTABANCARIA CBFAV ON CBFAV.ID = FAV.BANCOCREDITOID
LEFT JOIN SITRAWEBNEW.DBO.STATUSFATURAMENTO SRFAV ON SRFAV.ID = FAV.STATUSFATURAMENTOID
GO
CREATE OR ALTER  VIEW VW_CONSULTARELATMDFEEMITIDOSMOTORISTA AS
SELECT 
MANIF.MANIFESTOID,
MANIF.NRMANIFESTO,
MANIF.ANO,
MANIF.DATAEMISSAO,

--FILIAL EMISSÃO
MANIF.FILIALID AS FILIALEMISSAOID,
FILEMI.SIGLA AS FILIALEMISSAOSIGLA,

--FILIAL DESTINO
MANIF.FILIALDESTINOID AS FILIALDESTINOID,
FILDEST.SIGLA AS FILIALDESTINOSIGLA,

--MOTORISTA
MANIF.MOTORISTAID AS MOTID,
MOT.NOME AS MOTORISTANOME,
MOT.CPF AS MOTCPF,

--VEÍCULO
MANIF.PLACAVEICULO AS PLACAVEIC,

--VALOR DOCS
(SELECT SUM(VALORMERCADORIA) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN(SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID)) AS VALORMERCADORIA,
(SELECT SUM(PESOCUBADO) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (1,  3) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS PESOCUBCIF,
(SELECT SUM(PESOCUBADO) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (2,  4) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS PESOCUBFOB,
--(SELECT SUM(PESOCUBADO) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (5,  7) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS PESOCUBRED,
--(SELECT SUM(PESOCUBADO) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (6,  8) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS PESOCUBCON,
--(SELECT SUM(PESOCUBADO) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (9, 10) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS PESOCUBSUB,
(SELECT SUM(TOTALFRETE) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (1,  3) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS TOTALFRETECIF,
(SELECT SUM(TOTALFRETE) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (2,  4) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS TOTALFRETEFOB,
--(SELECT SUM(TOTALFRETE) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (5,  7) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS TOTALFRETERED,
--(SELECT SUM(TOTALFRETE) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (6,  8) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS TOTALFRETECON,
--(SELECT SUM(TOTALFRETE) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCID FROM DOCUMENTOS D WHERE D.TIPOFRETEID IN (9, 10) AND D.DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID))) AS TOTALFRETESUB,
(SELECT SUM(TOTALFRETE) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN (SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID)) AS VALORTOTALFRETE,

--CONTRATO DE FRETE
MANIF.CONTRATOID,
CF.NRCONTRATO,
CF.FILIALID AS FILEMICFID,
FILEMICF.SIGLA AS FILEMICFSIGLA,
--VALOR CONTRATO
CCF.VALORTOTAL AS TOTALCIOT

FROM MANIFESTO MANIF
LEFT OUTER JOIN CONTRATOFRETE CF ON CF.CONTRATOID = MANIF.CONTRATOID
LEFT OUTER JOIN CONTRATOCOMPFRETE CCF ON CCF.CONTRATOID = CF.CONTRATOID
LEFT OUTER JOIN SITRAWEBNEW.DBO.FILIAIS FILEMICF ON FILEMICF.FILIALID = CF.FILIALID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FILEMI ON FILEMI.FILIALID = MANIF.FILIALID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FILDEST ON FILDEST.FILIALID = MANIF.FILIALDESTINOID
INNER JOIN MOTORISTA MOT ON MOT.MOTORISTAID = MANIF.MOTORISTAID
GO
CREATE OR ALTER  VIEW VW_CONSULTARELATMDFEEMITIDOSGERAL AS
		SELECT 

CASE 	
		WHEN MANIF.TIPODOCUMENTOID = 2 THEN 'MANIFESTO ELETRONICO MDF-e'
		WHEN MANIF.TIPODOCUMENTOID = 7 THEN 'MANIFESTO MINUTA MDM' END AS TIPOMANIFESTO,
		
MANIF.MANIFESTOID,
MANIF.NRMANIFESTO,
MANIF.ANO,
MANIF.DATAEMISSAO,

--FILIAL EMISSÃO
MANIF.FILIALID AS FILIALEMISSAOID,
UPPER(FILENDORI.CIDADE) + '-' + UPPER(FILENDORI.ESTADO) AS FILIALEMISSAOSIGLA,

--FILIAL DESTINO
MANIF.FILIALDESTINOID AS FILIALDESTINOID,
UPPER(FILENDDEST.CIDADE) + '-' + UPPER(FILENDDEST.ESTADO) AS FILIALDESTINOSIGLA,

--VALOR DOCS
(SELECT SUM(VALORMERCADORIA) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN(SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID)) AS VALORMERCADORIA,
(SELECT 
	SUM(PESOCUBADO) 
FROM DOCUMENTOSCOMPOSICAOFRETE 
WHERE 
DOCID IN (SELECT 
			DOCID 
		  FROM DOCUMENTOS D 
		  WHERE 
			D.TIPOFRETEID IN (1, 3) 
				AND D.DOCID IN (SELECT 
									DOCUMENTOID 
								FROM MANIFESTO_DOC 
								WHERE 
									MANIFESTOID = MANIF.MANIFESTOID)
		)
) AS PESOCUBCIF,

(SELECT 
	SUM(PESOCUBADO) 
FROM DOCUMENTOSCOMPOSICAOFRETE 
WHERE 
DOCID IN (SELECT 
			DOCID 
		  FROM DOCUMENTOS D 
		  WHERE 
			D.TIPOFRETEID IN (2, 4) 
				AND D.DOCID IN (SELECT 
									DOCUMENTOID 
								FROM MANIFESTO_DOC 
								WHERE 
									MANIFESTOID = MANIF.MANIFESTOID)
		)
) AS PESOCUBFOB,

(SELECT 
	SUM(TOTALFRETE) 
FROM DOCUMENTOSCOMPOSICAOFRETE 
WHERE 
DOCID IN (SELECT 
			DOCID 
		  FROM DOCUMENTOS D 
		  WHERE 
			D.TIPOFRETEID IN (1, 3) 
				AND D.DOCID IN (SELECT 
									DOCUMENTOID 
								FROM MANIFESTO_DOC 
								WHERE 
									MANIFESTOID = MANIF.MANIFESTOID)
		)
) AS TOTALFRETECIF,

(SELECT 
	SUM(TOTALFRETE) 
FROM DOCUMENTOSCOMPOSICAOFRETE 
WHERE 
DOCID IN (SELECT 
			DOCID 
		  FROM DOCUMENTOS D 
		  WHERE 
			D.TIPOFRETEID IN (2, 4) 
				AND D.DOCID IN (SELECT 
									DOCUMENTOID 
								FROM MANIFESTO_DOC 
								WHERE 
									MANIFESTOID = MANIF.MANIFESTOID)
		)
) AS TOTALFRETEFOB,

(SELECT SUM(TOTALFRETE) FROM DOCUMENTOSCOMPOSICAOFRETE WHERE DOCID IN(SELECT DOCUMENTOID FROM MANIFESTO_DOC WHERE MANIFESTOID = MANIF.MANIFESTOID)) AS VALORTOTALFRETE,

--CONTRATO DE FRETE
MANIF.CONTRATOID,
CF.NRCONTRATO,
CF.FILIALID AS FILEMICFID,
FILEMICF.SIGLA AS FILEMICFSIGLA,
--VALOR CONTRATO
CCF.VALORTOTAL AS TOTALCIOT,
MANIF.PLACAVEICULO

FROM MANIFESTO MANIF
LEFT OUTER JOIN CONTRATOFRETE CF ON CF.CONTRATOID = MANIF.CONTRATOID
LEFT OUTER JOIN CONTRATOCOMPFRETE CCF ON CCF.CONTRATOID = CF.CONTRATOID
LEFT OUTER JOIN SITRAWEBNEW.DBO.FILIAIS FILEMICF ON FILEMICF.FILIALID = CF.FILIALID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FILEMI ON FILEMI.FILIALID = MANIF.FILIALID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FILDEST ON FILDEST.FILIALID = MANIF.FILIALDESTINOID
INNER JOIN MANIFESTOELETRONICO MDFE ON MDFE.MANIFESTOID = MANIF.MANIFESTOID AND MDFE.NRPROTOCOLOAUTORIZACAO IS NOT NULL
LEFT OUTER JOIN  SITRAWEBNEW.DBO.FILIALENDERECO AS FILENDDEST ON FILENDDEST.FILIALID = MANIF.FILIALDESTINOID
LEFT OUTER JOIN  SITRAWEBNEW.DBO.FILIALENDERECO AS FILENDORI ON FILENDORI.FILIALID = MANIF.FILIALID
GO

CREATE OR ALTER  VIEW VW_SELECTMINUTASGERARNFSE AS 
SELECT 
F.FILIALID
,F.FILIALNOME
,F.SIGLA AS FILIALSIGLA
,D.DOCID
,D.NUMERODOC
,D.DATAEMISSAO
,DCF.TOTALFRETE
,SD.STATUSDOCUMENTOID
,SD.SIGLA
,SD.DESCRICAO
,CD.CPFCNPJ DESCPFCNPJ
,CD.NOMEFANTASIA DESNOME
,CD.CLIENTEID DESID
,CD.CIDADE DESCIDADE
,CD.UF DESUF
,CR.CPFCNPJ REMCPFCNPJ
,CR.NOMEFANTASIA REMNOME
,CR.CLIENTEID REMID
,CR.CIDADE REMCIDADE
,CR.UF REMUF
,CP.CPFCNPJ PAGCPFCNPJ
,CP.NOMEFANTASIA PAGNOME
,CP.CLIENTEID PAGID
,CP.CIDADE PAGCIDADE
,CP.UF PAGUF
,D.LOCALENTREGACIDADE
,D.LOCALENTREGAUF
FROM DOCUMENTOS D
INNER JOIN DOCUMENTOSCOMPOSICAOFRETE DCF ON DCF.DOCID = D.DOCID
INNER JOIN CLIENTES CD ON CD.CLIENTEID = D.DESTINATARIOID
INNER JOIN CLIENTES CR ON CR.CLIENTEID = D.REMETENTEID
INNER JOIN CLIENTES CP ON CP.CLIENTEID = D.TOMADORID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS F ON F.FILIALID = D.FILIALID
INNER JOIN SITRAWEBNEW.DBO.STATUSDOCUMENTO SD ON SD.STATUSDOCUMENTOID = D.STATUSDOCUMENTOID
GO
CREATE OR ALTER  VIEW VW_PESQUISACOTACOESCTE AS 

SELECT 
C.COTID,
C.NUMEROCOTACAO,

--STATUS COTAÇÃO
C.STATUSCOTACAOID,
ST.SIGLA AS STSIGLA,
ST.DESCRICAO AS STDESC,

--FILIAL EMISSÃO
C.FILIALIDCADASTRO,
FILEMI.SIGLA AS FILEMISIGLA,
FILEMI.FILIALNOME AS FILEMINOME,

--FILIAL ORIGEM
C.FILIALID,
FILORI.SIGLA AS FILORISIGLA,
FILORI.FILIALNOME AS FILORINOME,

--TOMADOR
C.CLIENTETOMADORID,
CLI.CPFCNPJ AS TOMCPFCNPJ,
CLI.NOMEFANTASIA AS TOMNOME,

C.DATAEMISSAO,
C.DATAVALIDADE,
C.EMBALAGEM,

--COMPOSIÇÃO DO FRETE
CF.TOTALFRETE,
CF.PESOCUBADO,
CF.VOLUMES,
CF.PESO,
CF.MEDIDAS,
CF.VALORMERCADORIA,

C.LOCALCOLETAUF,
C.LOCALCOLETACIDADE,
C.LOCALENTREGAUF,
C.LOCALENTREGACIDADE,

--USUÁRIO DE CADASTRO
C.USUARIOIDCADASTRO,
USERCAD.USUARIONOME,

C.CONTATO,

--PRODUTO
C.PRODUTOID,
PROD.PRODUTODESC,

--VEÍCULO
C.VEICULOCALCULO,
TV.TIPOVEICULODESC,

--TIPO FRETE
C.TIPOFRETEID,
TF.TIPOFRETEDESC

FROM COTACAO C
LEFT JOIN SITRAWEBNEW.DBO.STATUSCOTACAO ST ON ST.STATUSCOTACAOID = C.STATUSCOTACAOID
LEFT JOIN SITRAWEBNEW.DBO.FILIAIS FILEMI ON FILEMI.FILIALID = C.FILIALIDCADASTRO
LEFT JOIN SITRAWEBNEW.DBO.FILIAIS FILORI ON FILORI.FILIALID = C.FILIALID
LEFT JOIN CLIENTES CLI ON CLI.CLIENTEID = C.CLIENTETOMADORID
LEFT JOIN COTACAOCOMPFRETE CF ON CF.COTID = C.COTID
LEFT JOIN SITRAWEBNEW.DBO.USUARIOS USERCAD ON USERCAD.USUARIOID = C.USUARIOIDCADASTRO
LEFT JOIN PRODUTOS PROD ON PROD.PRODUTOID = C.PRODUTOID
LEFT JOIN TIPOVEICULO TV ON TV.TIPOVEICULOID = C.VEICULOCALCULO
LEFT JOIN SITRAWEBNEW.DBO.TIPOFRETE TF ON TF.TIPOFRETEID = C.TIPOFRETEID
GO

CREATE OR ALTER  VIEW VW_CONSULTARELATCTEEMITIDOSRANKINGCLIENTE AS 

SELECT 
CPFCNPJ,
NOMEFANTASIA,
COUNT(QTDEDOCS) AS QTDEDOCS,
SUM(QTDEPESO) AS QTDEPESO,
SUM(QTDEPESOCUB) AS QTDEPESOCUB,
SUM(TOTALNFS) AS TOTALNFS,
SUM(TOTALFRETE) AS TOTALFRETE,
SUM(TOTALNOTA) AS TOTALNOTA,
0 AS TIPODOCUMENTOID,
'0' AS SIGLA,
FILSIGLA
FROM (
SELECT DISTINCT
CLI.CPFCNPJ,
CLI.NOMEFANTASIA,
DOC.DOCID AS QTDEDOCS,
DCF.PESO AS QTDEPESO,
DCF.PESOCUBADO AS QTDEPESOCUB,
DCF.VALORMERCADORIA AS TOTALNFS,
DCF.TOTALFRETE AS TOTALFRETE,
(SELECT SUM(DN.VOLUMES) FROM DOCUMENTONOTA DN WHERE DN.DOCID = DOC.DOCID) AS TOTALNOTA,
DOC.TIPODOCUMENTOID,
--TPDOC.SIGLA,
FIL.SIGLA AS FILSIGLA
FROM CLIENTES CLI
INNER JOIN DOCUMENTOS DOC ON DOC.TOMADORID = CLI.CLIENTEID
INNER JOIN DOCUMENTOSCOMPOSICAOFRETE DCF ON DCF.DOCID = DOC.DOCID
--INNER JOIN SITRAWEBNEW.DBO.TIPODOCUMENTO TPDOC ON TPDOC.TIPODOCUMENTOID = DOC.TIPODOCUMENTOID
INNER JOIN SITRAWEBNEW.DBO.FILIAIS FIL ON FIL.FILIALID = DOC.FILIALID
) AS TBLPRINC
GROUP BY CPFCNPJ, NOMEFANTASIA, --TIPODOCUMENTOID, --SIGLA
 FILSIGLA
GO

CREATE OR ALTER  VIEW VW_CONSULTARELATCLIENTESVENDEDOR AS 
		
SELECT
VC.ID AS VCID,
VC.CIF AS VCCIF,
VC.FOB AS VCFOB,
VC.FILIALIDCADASTRO AS VCFILID,
VC.DATACADASTRO AS VCDTCADASTRO,
VC.USUARIOIDCADASTRO AS VCUSERCAD,

VEND.CPFCNPJ AS VENDCPFCNPJ,
VEND.NOME AS VENDNOME,
VEND.COMISSAOCIF AS VENDCOMISSAOCIF,
VEND.COMISSAOFOB AS VENDCOMISSAOFOB,

CLI.CPFCNPJ AS CLICPFCNPJ,
CLI.RAZAOSOCIAL AS CLIRAZAOSOCIAL,
CLI.ENDERECO AS CLIENDERECO,
CLI.NUMERO AS CLINUMERO,
CLI.CIDADE AS CLICIDADE,
CLI.UF AS CLIUF,
CLI.CONTATO AS CLICONTATO,
CLI.TELEFONE AS CLITELEFONE

FROM VENDEDORESCLIENTE VC
INNER JOIN CLIENTES CLI ON CLI.VENDEDORID = VC.VENDEDORID AND CLI.CLIENTEID = VC.CLIENTEID
INNER JOIN VENDEDORES VEND ON VEND.VENDEDORID = VC.VENDEDORID
GO

CREATE OR ALTER  VIEW VW_CLIENTESELECT AS
SELECT
CLIENTEID
,C.FILIALID
,C.CPFCNPJ
,C.RAZAOSOCIAL
,C.NOMEFANTASIA
,C.CONTATO
,C.CEP
,C.ENDERECO
,C.NUMERO
,C.BAIRRO
,C.CIDADE
,C.UF
,C.COMPLEMENTO
,C.TELEFONE
,C.CELULAR
,C.INSCRICAOESTADUAL
,C.TIPOCLIENTE
,C.RAMOATIVIDADEID
,C.INSCRICAOESTADUALSUBSTITUICAOTRIBUTARIAUF
,C.INSCRICAOESTADUALSUBSTITUICAOTRIBUTARIA
,C.EMAILENVIODACTEXML
,C.ENVIARXMLDOCTE
,C.ENVIARDACTEDOCTEEMFORMATOPDF
,C.FREQUENCIAENVIOEMAILDACTEXML
,C.TIPOENVIOEMAILLOTEDACTEXML
,C.DATACADASTRO
,C.DATACREATE OR ALTER ACAO
,C.USUARIOIDCADASTRO
,C.USUARIOIDCREATE OR ALTER ACAO
,C.ATIVO
,C.PAGATDE
,C.DIFICILENTREGA
,C.CANHOTO
,C.CUBAGEM
,C.AGRUPARNFE
,V.CPFCNPJ AS VENDEDORCPFCNPJ
,V.NOME AS VENDEDORNOME
,C.VENDEDORID AS VENDEDORID
FROM CLIENTES C WITH(NOLOCK)
LEFT JOIN VENDEDORES V ON V.VENDEDORID = C.VENDEDORID
GO

