USE [SITRAWEBNEW]
GO
ALTER TABLE ESTADOS ADD REGIAO INT;
GO
ALTER TABLE ESTADOS ADD NOMEREGIAO VARCHAR(20);
GO
UPDATE ESTADOS SET REGIAO = 0 WHERE ESTADOID = '00';
UPDATE ESTADOS SET REGIAO = 1 WHERE ESTADOID IN ('11','12','13','14','15','16','17');
UPDATE ESTADOS SET REGIAO = 2 WHERE ESTADOID IN ('21','23','24','25','26','27','28','29');
UPDATE ESTADOS SET REGIAO = 3 WHERE ESTADOID IN ('31','32','33','35');
UPDATE ESTADOS SET REGIAO = 4 WHERE ESTADOID IN ('41','42','43');
UPDATE ESTADOS SET REGIAO = 5 WHERE ESTADOID IN ('50','51','52','53');
GO
UPDATE ESTADOS SET NOMEREGIAO = 'Norte' WHERE REGIAO = 1;
UPDATE ESTADOS SET NOMEREGIAO = 'Nordeste' WHERE REGIAO = 2;
UPDATE ESTADOS SET NOMEREGIAO = 'Sudeste' WHERE REGIAO = 3;
UPDATE ESTADOS SET NOMEREGIAO = 'Centro-Oeste' WHERE REGIAO = 4;
UPDATE ESTADOS SET NOMEREGIAO = 'Sul' WHERE REGIAO = 5;
GO
--TESTE DE DADOS DE SEPARACAO DE REGIAO
SELECT 
	'NA REGIAO '+ CAST(REGIAO AS VARCHAR(2)) + ' '+ NOMEREGIAO + ' POSSUI '+ CAST(COUNT(REGIAO) AS VARCHAR(2)) + ' ESTADOS' AS REGIOES 
	FROM SITRAWEBNEW.DBO.ESTADOS
WHERE REGIAO <> 0
GROUP BY REGIAO,NOMEREGIAO


