SELECT TOP(100) * FROM VW_SELECTEXTRATOCONCILIADO;
SELECT TOP(100) * FROM VW_SELECTEXTRATONAOCONCILIADO;

INSERT INTO CENTROSCUSTOS (CODIGO,DESCRICAO,DATACADASTRO,USUARIOIDCADASTRO,FILIALIDCADASTRO,DATAALTERACAO,USUARIOIDALTERACAO,FILIALIDALTERACAO)
VALUES (0,'RECEITAS',GETDATE(),66,24,NULL,NULL,NULL);
INSERT INTO SUBCUSTOS (CODIGO,DESCRICAO,CODIGOCONTABIL, CODIGOCONTABILREDUZIDO, DATACADASTRO,USUARIOIDCADASTRO,FILIALIDCADASTRO,DATAALTERACAO,USUARIOIDALTERACAO,FILIALIDALTERACAO)
VALUES (0,'RECEITAS',NULL,NULL,GETDATE(),66,24,NULL,NULL,NULL);

SELECT * FROM CENTROSCUSTOS
SELECT * FROM SUBCUSTOS
SELECT * FROM PLANOCONTAS


SELECT 
	CC.ID AS CentroCustoId
	,CC.DESCRICAO AS DescricaoCentroCusto
	,SC.Id as SubCustoId
	,SC.Descricao AS DescricaoSubCusto
FROM PlanoContas AS PC
INNER JOIN CentrosCustos AS CC ON CC.Id = PC.CentroCustoId
INNER JOIN Subcustos AS SC ON SC.ID = PC.SubcustoId